### ISSUE TITLE
UCC not compiling UT3Weapons

### ISSUE THREAD

**Issue by HellDragon-HK** [GreatEmerald/UT3Weapons#17]
You said open a new issue so here it is

When trying to run UCC make it doesn't even seem to detect UT3Weapons and is only doing the vehicles.

**Comment by GreatEmerald** [comment]
...because you need to add it to `EditPackages` in UT2004.ini.

**Comment by HellDragon-HK** [comment]
Oh right I forgot sorry, still new to this so bear with me please I'm an idiot

**Comment by HellDragon-HK** [comment]
In case you miss the edited message I'm moving it to a new comment here

EDIT-btw this is the UT3Style.u to remove right because I don't seem to have a UT3Weapons.u
EDIT2-Compiled without errors and now I have a UT3Weapons.u but not a UT3Style.u
EDIT3-Confirmed I installed UT3Weapons-b4.7z, it has UT3Style and not UT3Weapons

Also do you have any double-post rules or do you prefer new comments when possible?

**Comment by GreatEmerald** [comment]
I have no problems with double posting. I don't get notifications on edits at all.

Hm, good to know it compiles, but yea, the package used to be named UT3Style but then I changed it to UT3Weapons when I split UT3Vehicles off. I prefer UT3Weapons here, but I'm not sure if it works properly with that name? Something to test, perhaps.

**Comment by HellDragon-HK** [comment]
I was trying to point out if you noticed the current public pack is UT3Style still but it sounds like you just renamed it on this test version?
Btw you can probably close this one now since it was my own dumb mistake

**Comment by GreatEmerald** [comment]
No, that was renamed during the last UT3Vehicles release. I guess it was after the weapons release, so there's no official version with the new name yet.
